SELECT DISTINCT
	(RCRAPP1_PIDM)
FROM
	SORLCUR SC
  , RCRAPP1
  , (
		SELECT
			SGRSATT_PIDM
		  , MAX(SGRSATT_ATTS_CODE) KEEP (DENSE_RANK FIRST ORDER BY SGRSATT_TERM_CODE_EFF, SGRSATT_ACTIVITY_DATE DESC) SGRSATT_ATTS_CODE
		FROM
			SGRSATT
		GROUP BY
			SGRSATT_PIDM
	)
	SGRSATT
WHERE
	(
		(
			SC.SORLCUR_DEGC_CODE LIKE '%CERT%'
		)
		OR
		(
			SC.SORLCUR_ADMT_CODE IN ('3B','5A','5C','1P')
		)
		OR SC.SORLCUR_PROGRAM = 'UNDCG_0034'
		OR
		(
			SC.SORLCUR_PROGRAM           = 'NONDEG_0777'
			AND SGRSATT_ATTS_CODE NOT LIKE '%EDC%'
		)
	)
	AND SC.SORLCUR_TERM_CODE =
	(
		SELECT
			MAX(SC2.SORLCUR_TERM_CODE)
		FROM
			SORLCUR SC2
		WHERE
			SC.SORLCUR_PIDM             = SC2.SORLCUR_PIDM
			AND SC2.SORLCUR_PRIORITY_NO = 1
			AND SC2.SORLCUR_LMOD_CODE   = 'LEARNER'
	)
	AND SC.SORLCUR_SEQNO =
	(
		SELECT
			MAX(SC3.SORLCUR_SEQNO)
		FROM
			SORLCUR SC3
		WHERE
			SC.SORLCUR_PIDM             = SC3.SORLCUR_PIDM
			AND SC.SORLCUR_TERM_CODE    = SC3.SORLCUR_TERM_CODE
			AND SC3.SORLCUR_PRIORITY_NO = 1
			AND SC3.SORLCUR_LMOD_CODE   = 'LEARNER'
	)
	AND SC.SORLCUR_PIDM   =RCRAPP1_PIDM
	AND RCRAPP1_AIDY_CODE = :AIDY
	AND RCRAPP1_PIDM      = :PIDM
	AND SC.SORLCUR_PIDM   =SGRSATT_PIDM(+)
;